/* Generated by Pyrex 0.4 on Mon Jul 22 22:30:37 2002 */

#include "Python.h"


static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, char *name); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
struct spam {
  PyObject *parrot;
};
typedef struct spam spam;


static PyObject *__pyx_f_f(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_f(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct spam __pyx_v_s;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "ProjectsA:Python:Pyrex:Tests:Errors1:e_pyobinstruct.pyx":5 */

  /* "ProjectsA:Python:Pyrex:Tests:Errors1:e_pyobinstruct.pyx":6 */
  __pyx_1 = __Pyx_GetName(__pyx_b, "x"); if (!__pyx_1) goto __pyx_L1;
  Py_DECREF(__pyx_v_s.parrot);
  __pyx_v_s.parrot = __pyx_1;
  __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"f", (PyCFunction)__pyx_f_f, METH_VARARGS|METH_KEYWORDS, 0},
{0, 0, 0, 0}
};


DL_EXPORT(void) inite_pyobinstruct(void); /*proto*/
void inite_pyobinstruct(void) {
__pyx_m = Py_InitModule4("e_pyobinstruct", __pyx_methods, 0, 0, PYTHON_API_VERSION);
__pyx_b = PyImport_AddModule("__builtin__");
PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b);

/* "ProjectsA:Python:Pyrex:Tests:Errors1:e_pyobinstruct.pyx":1 */

/* "ProjectsA:Python:Pyrex:Tests:Errors1:e_pyobinstruct.pyx":4 */
return;
__pyx_L1:;
}

/* Runtime support code */

static PyObject *__Pyx_GetName(PyObject *dict, char *name) {
	PyObject *result;
	result = PyObject_GetAttrString(dict, name);
	if (!result)
		PyErr_SetString(PyExc_NameError, name);
	return result;
}
