/* Generated by Pyrex 0.9.8.6 on Sat Apr 10 10:45:13 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from excbug */


/* Declarations from implementation of excbug */





static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {0, 0, 0, 0}
};



/* Implementation of excbug */

static PyObject *__pyx_f_6excbug_iowrap(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6excbug_iowrap(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_f = 0;
  PyObject *__pyx_v_e;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"f",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_f)) return 0;
  Py_INCREF(__pyx_v_f);
  __pyx_v_e = Py_None; Py_INCREF(Py_None);
  /*try:*/ {
    __pyx_1 = PyObject_CallObject(__pyx_v_f, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L2;}
    __pyx_r = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L0;
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/Bugs/szabo/excbug.pyx":4 */
  __pyx_2 = PyErr_ExceptionMatches(PyExc_IOError);
  if (__pyx_2) {
    __pyx_filename = __pyx_f[0]; __pyx_lineno = 4; __Pyx_AddTraceback("excbug.iowrap");
    if (__Pyx_GetException(&__pyx_1, &__pyx_3, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;}
    Py_INCREF(__pyx_3);
    Py_DECREF(__pyx_v_e);
    __pyx_v_e = __pyx_3;
    Py_INCREF(__pyx_v_e);
    __pyx_r = __pyx_v_e;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L3;
  }
  goto __pyx_L1;
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("excbug.iowrap");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_e);
  Py_DECREF(__pyx_v_f);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"iowrap", (PyCFunction)__pyx_f_6excbug_iowrap, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initexcbug(void); /*proto*/
PyMODINIT_FUNC initexcbug(void) {
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("excbug", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("excbug");
}

static char *__pyx_filenames[] = {
  "excbug.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb) {
	PyThreadState *tstate = PyThreadState_Get();
	PyErr_Fetch(type, value, tb);
	PyErr_NormalizeException(type, value, tb);
	if (PyErr_Occurred())
		goto bad;
	if (!*tb) {
		printf("no traceback\n");
		*tb = Py_None;
		Py_INCREF(*tb);
	}
#if 1
	Py_INCREF(*type);
	Py_INCREF(*value);
	Py_INCREF(*tb);
	Py_XDECREF(tstate->exc_type);
	Py_XDECREF(tstate->exc_value);
	Py_XDECREF(tstate->exc_traceback);
	tstate->exc_type = *type;
	tstate->exc_value = *value;
	tstate->exc_traceback = *tb;
#endif
	return 0;
bad:
	Py_XDECREF(*type);
	Py_XDECREF(*value);
	Py_XDECREF(*tb);
	return -1;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
	while (t->p) {
		*t->p = PyString_FromStringAndSize(t->s, t->n - 1);
		if (!*t->p)
			return -1;
		if (t->i)
			PyString_InternInPlace(t->p);
		++t;
	}
	return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

/*-------------------------------------------------------------------------------*/

#include "code.h"
#include "frameobject.h"
#include "opcode.h"
#include "structmember.h"

PyFrameObject *
PyFrame_New_Debug(PyThreadState *tstate, PyCodeObject *code, PyObject *globals,
	    PyObject *locals)
{
	PyFrameObject *back = tstate->frame;
	PyFrameObject *f;
	PyObject *builtins;
	PyObject *builtin_object = PyString_InternFromString("__builtins__");

	//printf("tstate = %p\n", tstate);
	//printf("back = %p\n", back);

	builtins = PyDict_GetItem(globals, builtin_object);
	if (PyModule_Check(builtins)) {
		//printf("getting dict from builtins module\n");
		builtins = PyModule_GetDict(builtins);
		assert(!builtins || PyDict_Check(builtins));
	}
	//printf("builtins = %p\n", builtins);
	Py_INCREF(builtins);

	f = PyObject_GC_NewVar(PyFrameObject, &PyFrame_Type, 0);
	if (f == NULL) {
		Py_DECREF(builtins);
		return NULL;
	}

	f->f_code = code;
	f->f_valuestack = f->f_localsplus;
	f->f_locals = NULL;
	f->f_trace = NULL;
	f->f_exc_type = f->f_exc_value = f->f_exc_traceback = NULL;

	f->f_stacktop = f->f_valuestack;
	f->f_builtins = builtins;

	Py_XINCREF(back);
	f->f_back = back;
	
	Py_INCREF(code);
	Py_INCREF(globals);

	f->f_globals = globals;
	/* Most functions have CO_NEWLOCALS and CO_OPTIMIZED set. */
	locals = globals;
	Py_INCREF(locals);
	f->f_locals = locals;
	f->f_tstate = tstate;

	f->f_lasti = -1;
	f->f_lineno = code->co_firstlineno;
	f->f_iblock = 0;

	_PyObject_GC_TRACK(f);
	//printf("frame = %p\n", f);
	return f;
}

/*-------------------------------------------------------------------------------*/

static void __Pyx_AddTraceback(char *funcname) {
	PyObject *py_srcfile = 0;
	PyObject *py_funcname = 0;
	PyObject *py_globals = 0;
	PyObject *empty_tuple = 0;
	PyObject *empty_string = 0;
	PyCodeObject *py_code = 0;
	PyFrameObject *py_frame = 0;
	PyThreadState *tstate;
	
	py_srcfile = PyString_FromString(__pyx_filename);
	if (!py_srcfile) goto bad;
	py_funcname = PyString_FromString(funcname);
	if (!py_funcname) goto bad;
	py_globals = PyModule_GetDict(__pyx_m);
	if (!py_globals) goto bad;
	empty_tuple = PyTuple_New(0);
	if (!empty_tuple) goto bad;
	empty_string = PyString_FromString("");
	if (!empty_string) goto bad;
	py_code = PyCode_New(
		0,            /*int argcount,*/
		0,            /*int nlocals,*/
		0,            /*int stacksize,*/
		0,            /*int flags,*/
		empty_string, /*PyObject *code,*/
		empty_tuple,  /*PyObject *consts,*/
		empty_tuple,  /*PyObject *names,*/
		empty_tuple,  /*PyObject *varnames,*/
		empty_tuple,  /*PyObject *freevars,*/
		empty_tuple,  /*PyObject *cellvars,*/
		py_srcfile,   /*PyObject *filename,*/
		py_funcname,  /*PyObject *name,*/
		__pyx_lineno,   /*int firstlineno,*/
		empty_string  /*PyObject *lnotab*/
	);
	if (!py_code) goto bad;
	tstate = PyThreadState_Get();
#if 1
	py_frame = PyFrame_New_Debug(
		tstate,              /*PyThreadState *tstate,*/
		py_code,             /*PyCodeObject *code,*/
		py_globals,          /*PyObject *globals,*/
		0                    /*PyObject *locals*/
	);
#endif
#if 0
	if (!py_frame) goto bad;
	py_frame->f_lineno = __pyx_lineno;
#endif
#if 1
	PyTraceBack_Here(py_frame);
#endif
#if 0
	Py_XDECREF(tstate->curexc_traceback);
	tstate->curexc_traceback = NULL;
#endif
bad:;
	/*
	Py_XDECREF(py_srcfile);
	Py_XDECREF(py_funcname);
	Py_XDECREF(empty_tuple);
	Py_XDECREF(empty_string);
	Py_XDECREF(py_code);
	*/
#if 1
	Py_XDECREF(py_frame);
#endif
}
