/* Generated by Pyrex 0.9.3 on Sat Apr  8 17:52:35 2006 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

/* Declarations from inhcmethcall */


struct __pyx_obj_12inhcmethcall_Parrot {
  PyObject_HEAD
  struct __pyx_vtabstruct_12inhcmethcall_Parrot *__pyx_vtab;
};

struct __pyx_vtabstruct_12inhcmethcall_Parrot {
  void ((*describe)(struct __pyx_obj_12inhcmethcall_Parrot *));
};
static struct __pyx_vtabstruct_12inhcmethcall_Parrot *__pyx_vtabptr_12inhcmethcall_Parrot;


struct __pyx_obj_12inhcmethcall_Norwegian {
  struct __pyx_obj_12inhcmethcall_Parrot __pyx_base;
};

struct __pyx_vtabstruct_12inhcmethcall_Norwegian {
  struct __pyx_vtabstruct_12inhcmethcall_Parrot __pyx_base;
};
static struct __pyx_vtabstruct_12inhcmethcall_Norwegian *__pyx_vtabptr_12inhcmethcall_Norwegian;

static PyTypeObject *__pyx_ptype_12inhcmethcall_Parrot = 0;
static PyTypeObject *__pyx_ptype_12inhcmethcall_Norwegian = 0;

/* Implementation of inhcmethcall */

static void __pyx_f_12inhcmethcall_6Parrot_describe(struct __pyx_obj_12inhcmethcall_Parrot *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/Local/Projects/C/Pyrex/Source/Tests/8/inhcmethcall.pyx":4 */

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_WriteUnraisable("inhcmethcall.Parrot.describe");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static void __pyx_f_12inhcmethcall_9Norwegian_describe(struct __pyx_obj_12inhcmethcall_Norwegian *__pyx_v_self) {
  Py_INCREF((PyObject *)__pyx_v_self);

  /* "/Local/Projects/C/Pyrex/Source/Tests/8/inhcmethcall.pyx":10 */
  __pyx_vtabptr_12inhcmethcall_Parrot->describe(((struct __pyx_obj_12inhcmethcall_Parrot *)__pyx_v_self));

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_WriteUnraisable("inhcmethcall.Norwegian.describe");
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
}
static struct __pyx_vtabstruct_12inhcmethcall_Parrot __pyx_vtable_12inhcmethcall_Parrot;

static PyObject *__pyx_tp_new_12inhcmethcall_Parrot(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_12inhcmethcall_Parrot *p = (struct __pyx_obj_12inhcmethcall_Parrot *)o;
  *(struct __pyx_vtabstruct_12inhcmethcall_Parrot **)&p->__pyx_vtab = __pyx_vtabptr_12inhcmethcall_Parrot;
  return o;
}

static void __pyx_tp_dealloc_12inhcmethcall_Parrot(PyObject *o) {
  struct __pyx_obj_12inhcmethcall_Parrot *p = (struct __pyx_obj_12inhcmethcall_Parrot *)o;
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_12inhcmethcall_Parrot(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_12inhcmethcall_Parrot *p = (struct __pyx_obj_12inhcmethcall_Parrot *)o;
  return 0;
}

static int __pyx_tp_clear_12inhcmethcall_Parrot(PyObject *o) {
  struct __pyx_obj_12inhcmethcall_Parrot *p = (struct __pyx_obj_12inhcmethcall_Parrot *)o;
  return 0;
}

static struct PyMethodDef __pyx_methods_12inhcmethcall_Parrot[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Parrot = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Parrot = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Parrot = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Parrot = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_12inhcmethcall_Parrot = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "inhcmethcall.Parrot", /*tp_name*/
  sizeof(struct __pyx_obj_12inhcmethcall_Parrot), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_12inhcmethcall_Parrot, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Parrot, /*tp_as_number*/
  &__pyx_tp_as_sequence_Parrot, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Parrot, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Parrot, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_12inhcmethcall_Parrot, /*tp_traverse*/
  __pyx_tp_clear_12inhcmethcall_Parrot, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_12inhcmethcall_Parrot, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_12inhcmethcall_Parrot, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};
static struct __pyx_vtabstruct_12inhcmethcall_Norwegian __pyx_vtable_12inhcmethcall_Norwegian;

static PyObject *__pyx_tp_new_12inhcmethcall_Norwegian(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = __pyx_ptype_12inhcmethcall_Parrot->tp_new(t, a, k);
  struct __pyx_obj_12inhcmethcall_Norwegian *p = (struct __pyx_obj_12inhcmethcall_Norwegian *)o;
  *(struct __pyx_vtabstruct_12inhcmethcall_Norwegian **)&p->__pyx_base.__pyx_vtab = __pyx_vtabptr_12inhcmethcall_Norwegian;
  return o;
}

static void __pyx_tp_dealloc_12inhcmethcall_Norwegian(PyObject *o) {
  struct __pyx_obj_12inhcmethcall_Norwegian *p = (struct __pyx_obj_12inhcmethcall_Norwegian *)o;
  __pyx_ptype_12inhcmethcall_Parrot->tp_dealloc(o);
}

static int __pyx_tp_traverse_12inhcmethcall_Norwegian(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_12inhcmethcall_Norwegian *p = (struct __pyx_obj_12inhcmethcall_Norwegian *)o;
  __pyx_ptype_12inhcmethcall_Parrot->tp_traverse(o, v, a);
  return 0;
}

static int __pyx_tp_clear_12inhcmethcall_Norwegian(PyObject *o) {
  struct __pyx_obj_12inhcmethcall_Norwegian *p = (struct __pyx_obj_12inhcmethcall_Norwegian *)o;
  __pyx_ptype_12inhcmethcall_Parrot->tp_clear(o);
  return 0;
}

static struct PyMethodDef __pyx_methods_12inhcmethcall_Norwegian[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Norwegian = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Norwegian = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Norwegian = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Norwegian = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_12inhcmethcall_Norwegian = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "inhcmethcall.Norwegian", /*tp_name*/
  sizeof(struct __pyx_obj_12inhcmethcall_Norwegian), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_12inhcmethcall_Norwegian, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Norwegian, /*tp_as_number*/
  &__pyx_tp_as_sequence_Norwegian, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Norwegian, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Norwegian, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_12inhcmethcall_Norwegian, /*tp_traverse*/
  __pyx_tp_clear_12inhcmethcall_Norwegian, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_12inhcmethcall_Norwegian, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_12inhcmethcall_Norwegian, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initinhcmethcall(void); /*proto*/
PyMODINIT_FUNC initinhcmethcall(void) {
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("inhcmethcall", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_vtabptr_12inhcmethcall_Parrot = &__pyx_vtable_12inhcmethcall_Parrot;
  __pyx_vtable_12inhcmethcall_Parrot.describe = (void *)__pyx_f_12inhcmethcall_6Parrot_describe;
  if (PyType_Ready(&__pyx_type_12inhcmethcall_Parrot) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_12inhcmethcall_Parrot.tp_dict, __pyx_vtabptr_12inhcmethcall_Parrot) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Parrot", (PyObject *)&__pyx_type_12inhcmethcall_Parrot) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  __pyx_ptype_12inhcmethcall_Parrot = &__pyx_type_12inhcmethcall_Parrot;
  __pyx_vtabptr_12inhcmethcall_Norwegian = &__pyx_vtable_12inhcmethcall_Norwegian;
  __pyx_vtable_12inhcmethcall_Norwegian.__pyx_base = *__pyx_vtabptr_12inhcmethcall_Parrot;
  __pyx_vtable_12inhcmethcall_Norwegian.__pyx_base.describe = (void *)__pyx_f_12inhcmethcall_9Norwegian_describe;
  __pyx_type_12inhcmethcall_Norwegian.tp_base = __pyx_ptype_12inhcmethcall_Parrot;
  if (PyType_Ready(&__pyx_type_12inhcmethcall_Norwegian) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_12inhcmethcall_Norwegian.tp_dict, __pyx_vtabptr_12inhcmethcall_Norwegian) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Norwegian", (PyObject *)&__pyx_type_12inhcmethcall_Norwegian) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  __pyx_ptype_12inhcmethcall_Norwegian = &__pyx_type_12inhcmethcall_Norwegian;

  /* "/Local/Projects/C/Pyrex/Source/Tests/8/inhcmethcall.pyx":9 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("inhcmethcall");
}

static char *__pyx_filenames[] = {
  "inhcmethcall.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_WriteUnraisable(char *name) {
	PyObject *old_exc, *old_val, *old_tb;
	PyObject *ctx;
	PyErr_Fetch(&old_exc, &old_val, &old_tb);
	ctx = PyString_FromString(name);
	PyErr_Restore(old_exc, old_val, old_tb);
	if (!ctx)
		ctx = Py_None;
	PyErr_WriteUnraisable(ctx);
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
	PyObject *pycobj = 0;
	int result;
	
	pycobj = PyCObject_FromVoidPtr(vtable, 0);
	if (!pycobj)
		goto bad;
	if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
		goto bad;
	result = 0;
	goto done;

bad:
	result = -1;
done:
	Py_XDECREF(pycobj);
	return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
	PyObject *py_srcfile = 0;
	PyObject *py_funcname = 0;
	PyObject *py_globals = 0;
	PyObject *empty_tuple = 0;
	PyObject *empty_string = 0;
	PyCodeObject *py_code = 0;
	PyFrameObject *py_frame = 0;
	
	py_srcfile = PyString_FromString(__pyx_filename);
	if (!py_srcfile) goto bad;
	py_funcname = PyString_FromString(funcname);
	if (!py_funcname) goto bad;
	py_globals = PyModule_GetDict(__pyx_m);
	if (!py_globals) goto bad;
	empty_tuple = PyTuple_New(0);
	if (!empty_tuple) goto bad;
	empty_string = PyString_FromString("");
	if (!empty_string) goto bad;
	py_code = PyCode_New(
		0,            /*int argcount,*/
		0,            /*int nlocals,*/
		0,            /*int stacksize,*/
		0,            /*int flags,*/
		empty_string, /*PyObject *code,*/
		empty_tuple,  /*PyObject *consts,*/
		empty_tuple,  /*PyObject *names,*/
		empty_tuple,  /*PyObject *varnames,*/
		empty_tuple,  /*PyObject *freevars,*/
		empty_tuple,  /*PyObject *cellvars,*/
		py_srcfile,   /*PyObject *filename,*/
		py_funcname,  /*PyObject *name,*/
		__pyx_lineno,   /*int firstlineno,*/
		empty_string  /*PyObject *lnotab*/
	);
	if (!py_code) goto bad;
	py_frame = PyFrame_New(
		PyThreadState_Get(), /*PyThreadState *tstate,*/
		py_code,             /*PyCodeObject *code,*/
		py_globals,          /*PyObject *globals,*/
		0                    /*PyObject *locals*/
	);
	if (!py_frame) goto bad;
	py_frame->f_lineno = __pyx_lineno;
	PyTraceBack_Here(py_frame);
bad:
	Py_XDECREF(py_srcfile);
	Py_XDECREF(py_funcname);
	Py_XDECREF(empty_tuple);
	Py_XDECREF(empty_string);
	Py_XDECREF(py_code);
	Py_XDECREF(py_frame);
}
