/* Generated by Pyrex */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#ifndef WIN32
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from literals */



static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_NameLikeString2, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_name_like_string, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_thisparrotisresting, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k1p, 0, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k2p, 0, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k3p, 0, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, 0, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k5p, 0, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, 0, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k7p, 0, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k8p, 0, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k9p, 0, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k10p, 0, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k11p, 0, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k12p, 0, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k13p, 0, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_k14p, 0, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_k15p, 0, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_k16p, 0, __pyx_k16, sizeof(__pyx_k16)},
  {0, 0, 0, 0}
};

/* Implementation of literals */




static PyObject *__pyx_f_8literals_foo(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8literals_foo(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_a;
  PyObject *__pyx_v_a1;
  PyObject *__pyx_v_a2;
  PyObject *__pyx_v_a3;
  PyObject *__pyx_v_a4;
  PyObject *__pyx_v_b;
  PyObject *__pyx_v_b0a;
  PyObject *__pyx_v_b0b;
  PyObject *__pyx_v_b0c;
  PyObject *__pyx_v_b0d;
  PyObject *__pyx_v_b0e;
  PyObject *__pyx_v_b0f;
  PyObject *__pyx_v_b0g;
  PyObject *__pyx_v_b0h;
  PyObject *__pyx_v_b1;
  PyObject *__pyx_v_b2;
  PyObject *__pyx_v_b3;
  PyObject *__pyx_v_c;
  PyObject *__pyx_v_d;
  PyObject *__pyx_v_e;
  PyObject *__pyx_v_f;
  PyObject *__pyx_v_g;
  PyObject *__pyx_v_h;
  PyObject *__pyx_v_g1;
  PyObject *__pyx_v_h1;
  PyObject *__pyx_v_i;
  PyObject *__pyx_v_j;
  PyObject *__pyx_v_k;
  PyObject *__pyx_v_l;
  PyObject *__pyx_v_m;
  PyObject *__pyx_v_n;
  PyObject *__pyx_v_o;
  PyObject *__pyx_v_p;
  PyObject *__pyx_v_q;
  PyObject *__pyx_v_r;
  PyObject *__pyx_v_s;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  __pyx_v_a = Py_None; Py_INCREF(Py_None);
  __pyx_v_a1 = Py_None; Py_INCREF(Py_None);
  __pyx_v_a2 = Py_None; Py_INCREF(Py_None);
  __pyx_v_a3 = Py_None; Py_INCREF(Py_None);
  __pyx_v_a4 = Py_None; Py_INCREF(Py_None);
  __pyx_v_b = Py_None; Py_INCREF(Py_None);
  __pyx_v_b0a = Py_None; Py_INCREF(Py_None);
  __pyx_v_b0b = Py_None; Py_INCREF(Py_None);
  __pyx_v_b0c = Py_None; Py_INCREF(Py_None);
  __pyx_v_b0d = Py_None; Py_INCREF(Py_None);
  __pyx_v_b0e = Py_None; Py_INCREF(Py_None);
  __pyx_v_b0f = Py_None; Py_INCREF(Py_None);
  __pyx_v_b0g = Py_None; Py_INCREF(Py_None);
  __pyx_v_b0h = Py_None; Py_INCREF(Py_None);
  __pyx_v_b1 = Py_None; Py_INCREF(Py_None);
  __pyx_v_b2 = Py_None; Py_INCREF(Py_None);
  __pyx_v_b3 = Py_None; Py_INCREF(Py_None);
  __pyx_v_c = Py_None; Py_INCREF(Py_None);
  __pyx_v_d = Py_None; Py_INCREF(Py_None);
  __pyx_v_e = Py_None; Py_INCREF(Py_None);
  __pyx_v_f = Py_None; Py_INCREF(Py_None);
  __pyx_v_g = Py_None; Py_INCREF(Py_None);
  __pyx_v_h = Py_None; Py_INCREF(Py_None);
  __pyx_v_g1 = Py_None; Py_INCREF(Py_None);
  __pyx_v_h1 = Py_None; Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);
  __pyx_v_j = Py_None; Py_INCREF(Py_None);
  __pyx_v_k = Py_None; Py_INCREF(Py_None);
  __pyx_v_l = Py_None; Py_INCREF(Py_None);
  __pyx_v_m = Py_None; Py_INCREF(Py_None);
  __pyx_v_n = Py_None; Py_INCREF(Py_None);
  __pyx_v_o = Py_None; Py_INCREF(Py_None);
  __pyx_v_p = Py_None; Py_INCREF(Py_None);
  __pyx_v_q = Py_None; Py_INCREF(Py_None);
  __pyx_v_r = Py_None; Py_INCREF(Py_None);
  __pyx_v_s = Py_None; Py_INCREF(Py_None);

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":2 */
  __pyx_1 = PyInt_FromLong(42); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  Py_DECREF(__pyx_v_a);
  __pyx_v_a = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":3 */
  __pyx_1 = PyInt_FromLong(0123); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  Py_DECREF(__pyx_v_a1);
  __pyx_v_a1 = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":4 */
  __pyx_1 = PyInt_FromLong(0xabc); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;}
  Py_DECREF(__pyx_v_a2);
  __pyx_v_a2 = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":5 */
  __pyx_1 = PyInt_FromLong(0xDEF); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; goto __pyx_L1;}
  Py_DECREF(__pyx_v_a3);
  __pyx_v_a3 = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":6 */
  __pyx_1 = PyLong_FromString("1234567890L", 0, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 6; goto __pyx_L1;}
  Py_DECREF(__pyx_v_a4);
  __pyx_v_a4 = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":7 */
  __pyx_1 = PyFloat_FromDouble(42.88e17); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b);
  __pyx_v_b = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":8 */
  __pyx_1 = PyFloat_FromDouble(1.); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b0a);
  __pyx_v_b0a = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":9 */
  __pyx_1 = PyFloat_FromDouble(.1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b0b);
  __pyx_v_b0b = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":10 */
  __pyx_1 = PyFloat_FromDouble(1.1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b0c);
  __pyx_v_b0c = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":11 */
  __pyx_1 = PyFloat_FromDouble(1.e1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b0d);
  __pyx_v_b0d = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":12 */
  __pyx_1 = PyFloat_FromDouble(.1e1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b0e);
  __pyx_v_b0e = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":13 */
  __pyx_1 = PyFloat_FromDouble(1.1e1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b0f);
  __pyx_v_b0f = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":14 */
  __pyx_1 = PyFloat_FromDouble(1.1e-1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b0g);
  __pyx_v_b0g = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":15 */
  __pyx_1 = PyFloat_FromDouble(1e1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b0h);
  __pyx_v_b0h = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":16 */
  __pyx_1 = PyComplex_FromDoubles(0.0, 3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b1);
  __pyx_v_b1 = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":17 */
  __pyx_1 = PyComplex_FromDoubles(0.0, 3.1415); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b2);
  __pyx_v_b2 = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":18 */
  __pyx_1 = PyInt_FromLong('X'); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_DECREF(__pyx_v_b3);
  __pyx_v_b3 = __pyx_1;
  __pyx_1 = 0;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":19 */
  Py_INCREF(__pyx_k1p);
  Py_DECREF(__pyx_v_c);
  __pyx_v_c = __pyx_k1p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":20 */
  Py_INCREF(__pyx_n_thisparrotisresting);
  Py_DECREF(__pyx_v_d);
  __pyx_v_d = __pyx_n_thisparrotisresting;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":21 */
  Py_INCREF(__pyx_k3p);
  Py_DECREF(__pyx_v_e);
  __pyx_v_e = __pyx_k3p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":22 */
  Py_INCREF(__pyx_k4p);
  Py_DECREF(__pyx_v_f);
  __pyx_v_f = __pyx_k4p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":23 */
  Py_INCREF(__pyx_k5p);
  Py_DECREF(__pyx_v_g);
  __pyx_v_g = __pyx_k5p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":24 */
  Py_INCREF(__pyx_k6p);
  Py_DECREF(__pyx_v_h);
  __pyx_v_h = __pyx_k6p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":25 */
  Py_INCREF(__pyx_k7p);
  Py_DECREF(__pyx_v_g1);
  __pyx_v_g1 = __pyx_k7p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":27 */
  Py_INCREF(__pyx_k8p);
  Py_DECREF(__pyx_v_h1);
  __pyx_v_h1 = __pyx_k8p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":29 */
  Py_INCREF(__pyx_k9p);
  Py_DECREF(__pyx_v_i);
  __pyx_v_i = __pyx_k9p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":31 */
  Py_INCREF(__pyx_k10p);
  Py_DECREF(__pyx_v_j);
  __pyx_v_j = __pyx_k10p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":32 */
  Py_INCREF(__pyx_k11p);
  Py_DECREF(__pyx_v_k);
  __pyx_v_k = __pyx_k11p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":33 */
  Py_INCREF(__pyx_k12p);
  Py_DECREF(__pyx_v_l);
  __pyx_v_l = __pyx_k12p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":36 */
  Py_INCREF(__pyx_k13p);
  Py_DECREF(__pyx_v_m);
  __pyx_v_m = __pyx_k13p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":37 */
  Py_INCREF(__pyx_k14p);
  Py_DECREF(__pyx_v_n);
  __pyx_v_n = __pyx_k14p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":39 */
  Py_INCREF(__pyx_k15p);
  Py_DECREF(__pyx_v_o);
  __pyx_v_o = __pyx_k15p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":41 */
  Py_INCREF(__pyx_n_name_like_string);
  Py_DECREF(__pyx_v_p);
  __pyx_v_p = __pyx_n_name_like_string;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":42 */
  Py_INCREF(__pyx_n_NameLikeString2);
  Py_DECREF(__pyx_v_q);
  __pyx_v_q = __pyx_n_NameLikeString2;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":43 */
  Py_INCREF(__pyx_k18p);
  Py_DECREF(__pyx_v_r);
  __pyx_v_r = __pyx_k18p;

  /* "/Local/Projects/D/Pyrex/Source/Tests/1/literals.pyx":44 */
  Py_INCREF(__pyx_k19p);
  Py_DECREF(__pyx_v_s);
  __pyx_v_s = __pyx_k19p;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("literals.foo");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_a);
  Py_DECREF(__pyx_v_a1);
  Py_DECREF(__pyx_v_a2);
  Py_DECREF(__pyx_v_a3);
  Py_DECREF(__pyx_v_a4);
  Py_DECREF(__pyx_v_b);
  Py_DECREF(__pyx_v_b0a);
  Py_DECREF(__pyx_v_b0b);
  Py_DECREF(__pyx_v_b0c);
  Py_DECREF(__pyx_v_b0d);
  Py_DECREF(__pyx_v_b0e);
  Py_DECREF(__pyx_v_b0f);
  Py_DECREF(__pyx_v_b0g);
  Py_DECREF(__pyx_v_b0h);
  Py_DECREF(__pyx_v_b1);
  Py_DECREF(__pyx_v_b2);
  Py_DECREF(__pyx_v_b3);
  Py_DECREF(__pyx_v_c);
  Py_DECREF(__pyx_v_d);
  Py_DECREF(__pyx_v_e);
  Py_DECREF(__pyx_v_f);
  Py_DECREF(__pyx_v_g);
  Py_DECREF(__pyx_v_h);
  Py_DECREF(__pyx_v_g1);
  Py_DECREF(__pyx_v_h1);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_j);
  Py_DECREF(__pyx_v_k);
  Py_DECREF(__pyx_v_l);
  Py_DECREF(__pyx_v_m);
  Py_DECREF(__pyx_v_n);
  Py_DECREF(__pyx_v_o);
  Py_DECREF(__pyx_v_p);
  Py_DECREF(__pyx_v_q);
  Py_DECREF(__pyx_v_r);
  Py_DECREF(__pyx_v_s);
  return __pyx_r;
}



static struct PyMethodDef __pyx_methods[] = {
  {"foo", (PyCFunction)__pyx_f_8literals_foo, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initliterals(void); /*proto*/
PyMODINIT_FUNC initliterals(void) {
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("literals", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("literals");
}

static char *__pyx_filenames[] = {
  "literals.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
	while (t->p) {
		*t->p = PyString_InternFromString(t->s);
		if (!*t->p)
			return -1;
		++t;
	}
	return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
	while (t->p) {
		*t->p = PyString_FromStringAndSize(t->s, t->n - 1);
		if (!*t->p)
			return -1;
		++t;
	}
	return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
	PyObject *py_srcfile = 0;
	PyObject *py_funcname = 0;
	PyObject *py_globals = 0;
	PyObject *empty_tuple = 0;
	PyObject *empty_string = 0;
	PyCodeObject *py_code = 0;
	PyFrameObject *py_frame = 0;
	
	py_srcfile = PyString_FromString(__pyx_filename);
	if (!py_srcfile) goto bad;
	py_funcname = PyString_FromString(funcname);
	if (!py_funcname) goto bad;
	py_globals = PyModule_GetDict(__pyx_m);
	if (!py_globals) goto bad;
	empty_tuple = PyTuple_New(0);
	if (!empty_tuple) goto bad;
	empty_string = PyString_FromString("");
	if (!empty_string) goto bad;
	py_code = PyCode_New(
		0,            /*int argcount,*/
		0,            /*int nlocals,*/
		0,            /*int stacksize,*/
		0,            /*int flags,*/
		empty_string, /*PyObject *code,*/
		empty_tuple,  /*PyObject *consts,*/
		empty_tuple,  /*PyObject *names,*/
		empty_tuple,  /*PyObject *varnames,*/
		empty_tuple,  /*PyObject *freevars,*/
		empty_tuple,  /*PyObject *cellvars,*/
		py_srcfile,   /*PyObject *filename,*/
		py_funcname,  /*PyObject *name,*/
		__pyx_lineno,   /*int firstlineno,*/
		empty_string  /*PyObject *lnotab*/
	);
	if (!py_code) goto bad;
	py_frame = PyFrame_New(
		PyThreadState_Get(), /*PyThreadState *tstate,*/
		py_code,             /*PyCodeObject *code,*/
		py_globals,          /*PyObject *globals,*/
		0                    /*PyObject *locals*/
	);
	if (!py_frame) goto bad;
	py_frame->f_lineno = __pyx_lineno;
	PyTraceBack_Here(py_frame);
bad:
	Py_XDECREF(py_srcfile);
	Py_XDECREF(py_funcname);
	Py_XDECREF(empty_tuple);
	Py_XDECREF(empty_string);
	Py_XDECREF(py_code);
	Py_XDECREF(py_frame);
}
